### PR TITLE
mcombo works now

### PR DESCRIPTION
**Pull request by thoka**

### CODE REVIEW

**Comment by almereyda** [comment]
@thoka I suppose the PR https://github.com/TransforMap/iD/pull/14 from `unknown repository` can be closed then?

**Comment by thoka** [comment]
Yes, I did it myself.

**Comment by thoka** [comment]
@almereyda  please review this one

**Comment by species** [comment]
I'm impressed :-)
Do you like to send the pull request do openstreetmap/iD yourself?

**Comment by thoka** [comment]
Hm. Would I have to add changes to a clean openstreetmap fork first ?
Should we move our changes (transformap navbar, transformap presets etc) out to a transformap branch ?

**Comment by species** [comment]
Hm - maybe it would work if you create a pull request with ONLY your changes...
But it's way less error-prone if we create a a clean openstreetmap/iD fork, apply the mcombo patches and request a pull request then.
but please:
- we should read the CONTRIBUTING.md first and check if everything is in line with the guidelines
- please wait for my patches for fixing the dist/ issue #1 - I'm preparing a pull request right now for you.

**Comment by thoka** [comment]
We also should check the code more. I did not much work on the keyboard interface.
Lets get it run smoothly on our side and do a pull request after that ...

**Pull request merged**
